# __Pre-Processing__

### __Import Packages__

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import warnings

from library.sb_utils import save_file
warnings.filterwarnings('ignore')

### __Load Data__

In [2]:
df = pd.read_csv('./data/df_cleaned.csv')
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,54.954087,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,6.165950,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,54.954087,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,0.000759,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,6.165950,Graduate

In [3]:
# Encode Target
from sklearn.preprocessing import OrdinalEncoder

oenc = OrdinalEncoder()
df[['Target']] = oenc.fit_transform(df[['Target']])
df

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,54.954087,0.0
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,6.165950,2.0
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,54.954087,0.0
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,0.000759,2.0
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,6.165950,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1,6,9773,1,1,125.0,1,1,1,...,0,6,8,5,12.666667,0,15.5,2.8,0.000087,2.0
4420,1,1,2,9773,1,1,120.0,105,1,1,...,0,6,6,2,11.000000,0,11.1,0.6,104.712855,0.0
4421,1,1,1,9500,1,1,154.0,1,37,37,...,0,8,9,1,13.500000,0,13.9,-0.3,6.165950,0.0
4422,1,1,1,9147,1,1,180.0,1,37,37,...,0,5,6,5,12.000000,0,9.4,-0.8,0.000759,2.0
4423,1,10,1,9773,1,1,152.0,22,38,37,...,0,6,6,6,13.000000,0,12.7,3.7,0.019953,2.0

In [4]:
# Drop features we won't be using: Displaced, Unemployment rate, Inflation rate, GDP, as well as Target feature, which is put into its own df and we're removing the 'Enrolled' rows
df = df.drop(df[df['Target'] == 1].index).reset_index()
df_target = pd.DataFrame(df['Target'])
df = df.drop(['Displaced', 'Unemployment rate', 'Inflation rate', 'GDP', 'Target', 'index'], axis=1)
df

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nationality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations)
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0.000000,0,0,0,0,0,0.000000,0
1,1,15,1,9254,1,1,160.0,1,1,3,...,6,6,14.000000,0,0,6,6,6,13.666667,0
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,0,0.000000,0,0,6,0,0,0.000000,0
3,1,17,2,9773,1,1,122.0,1,38,37,...,8,6,13.428571,0,0,6,10,5,12.400000,0
4,2,39,1,8014,0,1,100.0,1,37,38,...,9,5,12.333333,0,0,6,6,6,13.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3625,1,1,6,9773,1,1,125.0,1,1,1,...,7,5,13.600000,0,0,6,8,5,12.666667,0
3626,1,1,2,9773,1,1,120.0,105,1,1,...,6,6,12.000000,0,0,6,6,2,11.000000,0
3627,1,1,1,9500,1,1,154.0,1,37,37,...,8,7,14.912500,0,0,8,9,1,13.500000,0
3628,1,1,1,9147,1,1,180.0,1,37,37,...,5,5,13.800000,0,0,5,6,5,12.000000,0
3629,1,10,1,9773,1,1,152.0,22,38,37,...,8,6,11.666667,0,0,6,6,6,13.000000,0

In [5]:
df_target.Target.unique()

array([0., 2.])

In [6]:
# Split df into numerical and categorical features
df_numerical = df[['Previous qualification (grade)', 'Admission grade', 'Age at enrollment', 'Curricular units 1st sem (credited)', 'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)', 'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)', 'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)', 'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)', 'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)', 'Curricular units 2nd sem (without evaluations)']]

df_categorical = df.drop(columns=df_numerical.columns)

In [7]:
# Numerical features to be scaled: Previous qualification (grade), Admission grade, Age at enrollment, Curricular units 1st sem (credited)	Curricular units 1st sem (enrolled)	Curricular units 1st sem (evaluations)	Curricular units 1st sem (approved)	Curricular units 1st sem (grade)	Curricular units 1st sem (without evaluations)	Curricular units 2nd sem (credited)	Curricular units 2nd sem (enrolled)	Curricular units 2nd sem (evaluations)	Curricular units 2nd sem (approved)	Curricular units 2nd sem (grade)	Curricular units 2nd sem (without evaluations) 
df_numerical

,Previous qualification (grade),Admission grade,Age at enrollment,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations)
0,122.0,127.3,20,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0
1,160.0,142.5,19,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0
2,122.0,124.8,19,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0
3,122.0,119.6,20,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0
4,100.0,141.5,45,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3625,125.0,122.2,19,0,6,7,5,13.600000,0,0,6,8,5,12.666667,0
3626,120.0,119.0,18,0,6,6,6,12.000000,0,0,6,6,2,11.000000,0
3627,154.0,149.5,30,0,7,8,7,14.912500,0,0,8,9,1,13.500000,0
3628,180.0,153.8,20,0,5,5,5,13.800000,0,0,5,6,5,12.000000,0
3629,152.0,152.0,22,0,6,8,6,11.666667,0,0,6,6,6,13.000000,0

In [8]:
df_numerical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3630 entries, 0 to 3629
Data columns (total 15 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Previous qualification (grade)                  3630 non-null   float64
 1   Admission grade                                 3630 non-null   float64
 2   Age at enrollment                               3630 non-null   int64
 3   Curricular units 1st sem (credited)             3630 non-null   int64
 4   Curricular units 1st sem (enrolled)             3630 non-null   int64
 5   Curricular units 1st sem (evaluations)          3630 non-null   int64
 6   Curricular units 1st sem (approved)             3630 non-null   int64
 7   Curricular units 1st sem (grade)                3630 non-null   float64
 8   Curricular units 1st sem (without evaluations)  3630 non-null   int64
 9   Curricular units 2nd sem (credited)             3630 non-null   int64
 10  Curricular units 2nd sem (enrolled)             3630 non-null   int64
 11  Curricular units 2nd sem (evaluations)          3630 non-null   int64
 12  Curricular units 2nd sem (approved)             3630 non-null   int64
 13  Curricular units 2nd sem (grade)                3630 non-null   float64
 14  Curricular units 2nd sem (without evaluations)  3630 non-null   int64
dtypes: float64(4), int64(11)
memory usage: 425.5 KB

In [9]:
df_categorical

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Nationality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,International
0,1,17,5,171,1,1,1,19,12,5,9,0,0,1,1,0,0
1,1,15,1,9254,1,1,1,1,3,3,3,0,0,0,1,0,0
2,1,1,5,9070,1,1,1,37,37,9,9,0,0,0,1,0,0
3,1,17,2,9773,1,1,1,38,37,5,3,0,0,1,0,0,0
4,2,39,1,8014,0,1,1,37,38,9,9,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3625,1,1,6,9773,1,1,1,1,1,5,4,0,0,1,1,0,0
3626,1,1,2,9773,1,1,105,1,1,9,9,0,1,0,0,0,1
3627,1,1,1,9500,1,1,1,37,37,9,9,0,0,1,0,1,0
3628,1,1,1,9147,1,1,1,37,37,7,4,0,0,1,0,1,0
3629,1,10,1,9773,1,1,22,38,37,5,9,0,0,1,0,0,1

### __Scale Numerical Features and Encode for Categorical Features__

In [10]:
# Scale
scaler = preprocessing.StandardScaler()
scaled_df = scaler.fit_transform(df_numerical)
scaled_df = pd.DataFrame(scaled_df, columns=df_numerical.columns)
scaled_df.head()

,Previous qualification (grade),Admission grade,Age at enrollment,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations)
0,-0.825034,0.000415,-0.442212,-0.304517,-2.465538,-1.883107,-1.480034,-2.083224,-0.189871,-0.287686,-2.782691,-1.958586,-1.429014,-1.831085,-0.190148
1,2.045805,1.040849,-0.569976,-0.304517,-0.131288,-0.483214,0.373306,0.685217,-0.189871,-0.287686,-0.131002,-0.444817,0.468555,0.662383,-0.190148
2,-0.825034,-0.170709,-0.569976,-0.304517,-0.131288,-1.883107,-1.480034,-2.083224,-0.189871,-0.287686,-0.131002,-1.958586,-1.429014,-1.831085,-0.190148
3,-0.825034,-0.526647,-0.442212,-0.304517,-0.131288,-0.016583,0.373306,0.572219,-0.189871,-0.287686,-0.131002,0.564362,0.152293,0.431281,-0.190148
4,-2.487099,0.972400,2.751894,-0.304517,-0.131288,0.216733,0.064416,0.355641,-0.189871,-0.287686,-0.131002,-0.444817,0.468555,0.540750,-0.190148

In [11]:
scaled_df.describe().loc['std']

Previous qualification (grade)                    1.000138
Admission grade                                   1.000138
Age at enrollment                                 1.000138
Curricular units 1st sem (credited)               1.000138
Curricular units 1st sem (enrolled)               1.000138
Curricular units 1st sem (evaluations)            1.000138
Curricular units 1st sem (approved)               1.000138
Curricular units 1st sem (grade)                  1.000138
Curricular units 1st sem (without evaluations)    1.000138
Curricular units 2nd sem (credited)               1.000138
Curricular units 2nd sem (enrolled)               1.000138
Curricular units 2nd sem (evaluations)            1.000138
Curricular units 2nd sem (approved)               1.000138
Curricular units 2nd sem (grade)                  1.000138
Curricular units 2nd sem (without evaluations)    1.000138
Name: std, dtype: float64

# Target Encoding
Switching here to try target encoding instead of one hot encoding. This should really be done after the test train split so we avoid data leakage.

In [12]:
# One-hot encoding
# encoder = preprocessing.OneHotEncoder(handle_unknown='ignore')
# encoded_df = encoder.fit_transform(df_categorical)
# encoded_df = pd.DataFrame(encoded_df.toarray(), columns=encoder.get_feature_names_out(df_categorical.columns))
# encoded_df.head()

In [13]:
from sklearn.model_selection import KFold

# df['marital_status_enc'] = 0
# kf = KFold(n_splits=5, shuffle=True, random_state=10)

# for train_idx, val_idx in kf.split(df):
#     train, val = df.iloc[train_idx], df.iloc[val_idx]
#     means = train.groupby('Marital status')['Target'].mean()
#     df.loc[val_idx, 'martial_status_enc'] = df.loc[val_idx, 'Marital status'].map(means)

In [14]:
def target_encoding(column, target='Target', df=df):
    '''
    Function to target encode categorical variables because they aren't simple booleans and we would have
    almost 250 columns if we did one hot encoding.
    '''
    new_col_name = str(column) + '_enc' # new column name for encoded variable
    if new_col_name in df.columns:
        raise NameError('Column already encoded')
    print(new_col_name)
    df[new_col_name] = 0                # allocate column
    kf = KFold(n_splits=5, shuffle=True, random_state=10) # perform split

    for tidx, vidx in kf.split(df):
    # loop through training and validation folds. Get mean of training fold and apply it to validation fold
        train, val = df.iloc[tidx], df.iloc[vidx]
        means = train.groupby(column)[target].mean()
        df.loc[vidx, new_col_name] = df.loc[vidx, column].map(means).fillna(df[target].mean())

In [15]:
encoded_df = df_categorical.join(df_target)

for col in encoded_df.columns:
    if col not in ['Target']:
        target_encoding(col, df=encoded_df)

Marital status_enc
Application mode_enc
Application order_enc
Course_enc
Daytime/evening attendance	_enc
Previous qualification_enc
Nationality_enc
Mother's qualification_enc
Father's qualification_enc
Mother's occupation_enc
Father's occupation_enc
Educational special needs_enc
Debtor_enc
Tuition fees up to date_enc
Gender_enc
Scholarship holder_enc
International_enc

In [16]:
encoded_df.drop(columns=encoded_df.columns[:len(df_categorical.columns)+1], inplace=True)
encoded_df

,Marital status_enc,Application mode_enc,Application order_enc,Course_enc,Daytime/evening attendance\t_enc,Previous qualification_enc,Nationality_enc,Mother's qualification_enc,Father's qualification_enc,Mother's occupation_enc,Father's occupation_enc,Educational special needs_enc,Debtor_enc,Tuition fees up to date_enc,Gender_enc,Scholarship holder_enc,International_enc
0,1.260274,1.309028,1.234043,1.133333,1.248442,1.287309,1.214538,1.313002,1.172414,1.292754,1.252616,1.217846,1.310990,1.390507,0.867203,1.036066,1.214538
1,1.232995,1.473684,1.125253,1.029586,1.219946,1.265205,1.190543,1.297533,1.195402,1.268293,1.236220,1.190675,1.283652,0.115000,0.852261,1.008411,1.190543
2,1.260274,1.517552,1.234043,1.374150,1.248442,1.287309,1.214538,1.075301,1.140000,1.253589,1.252616,1.217846,1.310990,0.120907,0.867203,1.036066,1.214538
3,1.264763,1.278459,1.347826,1.310924,1.244890,1.282988,1.216378,1.433862,1.150000,1.284507,1.291339,1.219087,1.307336,1.384067,1.402720,1.023910,1.216378
4,0.914498,0.740038,1.165743,1.265060,1.020649,1.302287,1.232993,1.115442,1.431818,1.272038,1.272198,1.235110,1.327646,1.398972,1.412632,1.060422,1.232993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3625,1.274932,1.518094,1.440860,1.349794,1.262378,1.302287,1.232993,1.312139,1.250426,1.277457,1.131148,1.235110,1.327646,1.398972,0.896414,1.060422,1.232993
3626,1.264763,1.511979,1.347826,1.310924,1.244890,1.282988,1.217080,1.300578,1.228130,1.266145,1.226190,1.219087,0.490446,0.125984,1.402720,1.023910,1.323944
3627,1.260274,1.517552,1.134557,1.673704,1.248442,1.287309,1.214538,1.075301,1.140000,1.253589,1.252616,1.217846,1.310990,1.390507,1.398953,1.719116,1.214538
3628,1.265862,1.524064,1.148545,1.040359,1.256699,1.291546,1.226216,1.102941,1.144254,1.250000,1.099174,1.226435,1.322957,1.398329,1.395668,1.723537,1.226216
3629,1.232995,1.000000,1.125253,1.300412,1.219946,1.265205,1.111111,1.375000,1.111386,1.287425,1.205926,1.190675,1.283652,1.361821,1.366160,1.008411,1.171429

In [17]:
encoded_df.isnull().sum()

Marital status_enc                  0
Application mode_enc                0
Application order_enc               0
Course_enc                          0
Daytime/evening attendance\t_enc    0
Previous qualification_enc          0
Nationality_enc                     0
Mother's qualification_enc          0
Father's qualification_enc          0
Mother's occupation_enc             0
Father's occupation_enc             0
Educational special needs_enc       0
Debtor_enc                          0
Tuition fees up to date_enc         0
Gender_enc                          0
Scholarship holder_enc              0
International_enc                   0
dtype: int64

In [19]:
df_features = pd.concat([encoded_df, scaled_df], axis=1)
df_features.head()

,Marital status_enc,Application mode_enc,Application order_enc,Course_enc,Daytime/evening attendance\t_enc,Previous qualification_enc,Nationality_enc,Mother's qualification_enc,Father's qualification_enc,Mother's occupation_enc,...,Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations)
0,1.260274,1.309028,1.234043,1.133333,1.248442,1.287309,1.214538,1.313002,1.172414,1.292754,...,-1.883107,-1.480034,-2.083224,-0.189871,-0.287686,-2.782691,-1.958586,-1.429014,-1.831085,-0.190148
1,1.232995,1.473684,1.125253,1.029586,1.219946,1.265205,1.190543,1.297533,1.195402,1.268293,...,-0.483214,0.373306,0.685217,-0.189871,-0.287686,-0.131002,-0.444817,0.468555,0.662383,-0.190148
2,1.260274,1.517552,1.234043,1.374150,1.248442,1.287309,1.214538,1.075301,1.140000,1.253589,...,-1.883107,-1.480034,-2.083224,-0.189871,-0.287686,-0.131002,-1.958586,-1.429014,-1.831085,-0.190148
3,1.264763,1.278459,1.347826,1.310924,1.244890,1.282988,1.216378,1.433862,1.150000,1.284507,...,-0.016583,0.373306,0.572219,-0.189871,-0.287686,-0.131002,0.564362,0.152293,0.431281,-0.190148
4,0.914498,0.740038,1.165743,1.265060,1.020649,1.302287,1.232993,1.115442,1.431818,1.272038,...,0.216733,0.064416,0.355641,-0.189871,-0.287686,-0.131002,-0.444817,0.468555,0.540750,-0.190148

In [20]:
df_target.head()

   Target
0     0.0
1     2.0
2     0.0
3     2.0
4     2.0

In [21]:
df_target.value_counts()

Target
2.0       2209
0.0       1421
Name: count, dtype: int64

## __Test-Train Split__

In [22]:
Xtrain, Xtest, ytrain, ytest = train_test_split(df_features, df_target, train_size=0.75)

Because some categorical features have many labels, like the occupation columns, it may be better to do target encoding instead. But I will change that if the current implementation has a large effect on the model training in the next notebook.

In [24]:
datapath = './data/'
save_file(df, 'df_cleaned_processed.csv', datapath)

A file already exists with this name.

Writing file.  "./data/df_cleaned_processed.csv"

## __Save Data__

In [25]:
datapath = './data/'
save_file(df_features, 'df_features.csv', datapath)
save_file(df_target, 'df_target.csv', datapath)
save_file(Xtrain, 'Xtrain.csv', datapath)
save_file(ytrain, 'ytrain.csv', datapath)
save_file(Xtest, 'Xtest.csv', datapath)
save_file(ytest, 'ytest.csv', datapath)

print('Data Preprocessing and Preparation completed successfully.')

A file already exists with this name.

Writing file.  "./data/df_features.csv"
A file already exists with this name.

Writing file.  "./data/df_target.csv"
A file already exists with this name.

Writing file.  "./data/Xtrain.csv"
A file already exists with this name.

Writing file.  "./data/ytrain.csv"
A file already exists with this name.

Writing file.  "./data/Xtest.csv"
A file already exists with this name.

Writing file.  "./data/ytest.csv"
Data Preprocessing and Preparation completed successfully.